use crate::{io::BufferReadable, util::code_err::CodeParseError};

#[repr(u8)]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Instruction {
    Nop,
    Aconst_null,
    Iconst_m1,
    Iconst_0,
    Iconst_1,
    Iconst_2,
    Iconst_3,
    Iconst_4,
    Iconst_5,
    Lconst_0,
    Lconst_1,
    Fconst_0,
    Fconst_1,
    Fconst_2,
    Dconst_0,
    Dconst_1,
    Bipush,
    Sipush,
    Ldc,
    Ldc_w,
    Ldc2_w,
    Iload,
    Lload,
    Fload,
    Dload,
    Aload,
    Iload_0,
    Iload_1,
    Iload_2,
    Iload_3,
    Lload_0,
    Lload_1,
    Lload_2,
    Lload_3,
    Fload_0,
    Fload_1,
    Fload_2,
    Fload_3,
    Dload_0,
    Dload_1,
    Dload_2,
    Dload_3,
    Aload_0,
    Aload_1,
    Aload_2,
    Aload_3,
    Iaload,
    Laload,
    Faload,
    Daload,
    Aaload,
    Baload,
    Caload,
    Saload,
    Istore,
    Lstore,
    Fstore,
    Dstore,
    Astore,
    Istore_0,
    Istore_1,
    Istore_2,
    Istore_3,
    Lstore_0,
    Lstore_1,
    Lstore_2,
    Lstore_3,
    Fstore_0,
    Fstore_1,
    Fstore_2,
    Fstore_3,
    Dstore_0,
    Dstore_1,
    Dstore_2,
    Dstore_3,
    Astore_0,
    Astore_1,
    Astore_2,
    Astore_3,
    Iastore,
    Lastore,
    Fastore,
    Dastore,
    Aastore,
    Bastore,
    Castore,
    Sastore,
    Pop,
    Pop2,
    Dup,
    Dup_x1,
    Dup_x2,
    Dup2,
    Dup2_x1,
    Dup2_x2,
    Swap,
    Iadd,
    Ladd,
    Fadd,
    Dadd,
    Isub,
    Lsub,
    Fsub,
    Dsub,
    Imul,
    Lmul,
    Fmul,
    Dmul,
    Idiv,
    Ldiv,
    Fdiv,
    Ddiv,
    Irem,
    Lrem,
    Frem,
    Drem,
    Ineg,
    Lneg,
    Fneg,
    Dneg,
    Ishl,
    Lshl,
    Ishr,
    Lshr,
    Iushr,
    Lushr,
    Iand,
    Land,
    Ior,
    Lor,
    Ixor,
    Lxor,
    Iinc,
    I2l,
    I2f,
    I2d,
    L2i,
    L2f,
    L2d,
    F2i,
    F2l,
    F2d,
    D2i,
    D2l,
    D2f,
    I2b,
    I2c,
    I2s,
    Lcmp,
    Fcmpl,
    Fcmpg,
    Dcmpl,
    Dcmpg,
    Ifeq,
    Ifne,
    Iflt,
    Ifge,
    Ifgt,
    Ifle,
    If_icmpeq,
    If_icmpne,
    If_icmplt,
    If_icmpge,
    If_icmpgt,
    If_icmple,
    If_acmpeq,
    If_acmpne,
    Goto,
    Jsr,
    Ret,
    Tableswitch,
    Lookupswitch,
    Ireturn,
    Lreturn,
    Freturn,
    Dreturn,
    Areturn,
    Return,
    Getstatic,
    Putstatic,
    Getfield,
    Putfield,
    Invokevirtual,
    Invokespecial,
    Invokestatic,
    Invokeinterface,
    Invokedynamic,
    New,
    Newarray,
    Arraylength,
    Athrow,
    Checkcast,
    Instanceof,
    Monitorenter,
    Monitorexit,
    Wide,
    Multianewarray,
    Ifnull,
    Ifnonnull,
    Goto_w,
    Jsr_w,
}

impl Instruction {
    pub fn load(reader: &mut Box<dyn BufferReadable>) -> Result<Instruction, CodeParseError> {
        match reader
            .read_byte()
            .map_err(|x| CodeParseError::InvalidFormat)?
        {
            0 => Ok(Instruction::Nop),
            1 => Ok(Instruction::Aconst_null),
            2 => Ok(Instruction::Iconst_m1),
            3 => Ok(Instruction::Iconst_0),
            4 => Ok(Instruction::Iconst_1),
            5 => Ok(Instruction::Iconst_2),
            6 => Ok(Instruction::Iconst_3),
            7 => Ok(Instruction::Iconst_4),
            8 => Ok(Instruction::Iconst_5),
            9 => Ok(Instruction::Lconst_0),
            10 => Ok(Instruction::Lconst_1),
            11 => Ok(Instruction::Fconst_0),
            12 => Ok(Instruction::Fconst_1),
            13 => Ok(Instruction::Fconst_2),
            14 => Ok(Instruction::Dconst_0),
            15 => Ok(Instruction::Dconst_1),
            16 => Ok(Instruction::Bipush),
            17 => Ok(Instruction::Sipush),
            18 => Ok(Instruction::Ldc),
            19 => Ok(Instruction::Ldc_w),
            20 => Ok(Instruction::Ldc2_w),
            21 => Ok(Instruction::Iload),
            22 => Ok(Instruction::Lload),
            23 => Ok(Instruction::Fload),
            24 => Ok(Instruction::Dload),
            25 => Ok(Instruction::Aload),
            26 => Ok(Instruction::Iload_0),
            27 => Ok(Instruction::Iload_1),
            28 => Ok(Instruction::Iload_2),
            29 => Ok(Instruction::Iload_3),
            30 => Ok(Instruction::Lload_0),
            31 => Ok(Instruction::Lload_1),
            32 => Ok(Instruction::Lload_2),
            33 => Ok(Instruction::Lload_3),
            34 => Ok(Instruction::Fload_0),
            35 => Ok(Instruction::Fload_1),
            36 => Ok(Instruction::Fload_2),
            37 => Ok(Instruction::Fload_3),
            38 => Ok(Instruction::Dload_0),
            39 => Ok(Instruction::Dload_1),
            40 => Ok(Instruction::Dload_2),
            41 => Ok(Instruction::Dload_3),
            42 => Ok(Instruction::Aload_0),
            43 => Ok(Instruction::Aload_1),
            44 => Ok(Instruction::Aload_2),
            45 => Ok(Instruction::Aload_3),
            46 => Ok(Instruction::Iaload),
            47 => Ok(Instruction::Laload),
            48 => Ok(Instruction::Faload),
            49 => Ok(Instruction::Daload),
            50 => Ok(Instruction::Aaload),
            51 => Ok(Instruction::Baload),
            52 => Ok(Instruction::Caload),
            53 => Ok(Instruction::Saload),
            54 => Ok(Instruction::Istore),
            55 => Ok(Instruction::Lstore),
            56 => Ok(Instruction::Fstore),
            57 => Ok(Instruction::Dstore),
            58 => Ok(Instruction::Astore),
            59 => Ok(Instruction::Istore_0),
            60 => Ok(Instruction::Istore_1),
            61 => Ok(Instruction::Istore_2),
            62 => Ok(Instruction::Istore_3),
            63 => Ok(Instruction::Lstore_0),
            64 => Ok(Instruction::Lstore_1),
            65 => Ok(Instruction::Lstore_2),
            66 => Ok(Instruction::Lstore_3),
            67 => Ok(Instruction::Fstore_0),
            68 => Ok(Instruction::Fstore_1),
            69 => Ok(Instruction::Fstore_2),
            70 => Ok(Instruction::Fstore_3),
            71 => Ok(Instruction::Dstore_0),
            72 => Ok(Instruction::Dstore_1),
            73 => Ok(Instruction::Dstore_2),
            74 => Ok(Instruction::Dstore_3),
            75 => Ok(Instruction::Astore_0),
            76 => Ok(Instruction::Astore_1),
            77 => Ok(Instruction::Astore_2),
            78 => Ok(Instruction::Astore_3),
            79 => Ok(Instruction::Iastore),
            80 => Ok(Instruction::Lastore),
            81 => Ok(Instruction::Fastore),
            82 => Ok(Instruction::Dastore),
            83 => Ok(Instruction::Aastore),
            84 => Ok(Instruction::Bastore),
            85 => Ok(Instruction::Castore),
            86 => Ok(Instruction::Sastore),
            87 => Ok(Instruction::Pop),
            88 => Ok(Instruction::Pop2),
            89 => Ok(Instruction::Dup),
            90 => Ok(Instruction::Dup_x1),
            91 => Ok(Instruction::Dup_x2),
            92 => Ok(Instruction::Dup2),
            93 => Ok(Instruction::Dup2_x1),
            94 => Ok(Instruction::Dup2_x2),
            95 => Ok(Instruction::Swap),
            96 => Ok(Instruction::Iadd),
            97 => Ok(Instruction::Ladd),
            98 => Ok(Instruction::Fadd),
            99 => Ok(Instruction::Dadd),
            100 => Ok(Instruction::Isub),
            101 => Ok(Instruction::Lsub),
            102 => Ok(Instruction::Fsub),
            103 => Ok(Instruction::Dsub),
            104 => Ok(Instruction::Imul),
            105 => Ok(Instruction::Lmul),
            106 => Ok(Instruction::Fmul),
            107 => Ok(Instruction::Dmul),
            108 => Ok(Instruction::Idiv),
            109 => Ok(Instruction::Ldiv),
            110 => Ok(Instruction::Fdiv),
            111 => Ok(Instruction::Ddiv),
            112 => Ok(Instruction::Irem),
            113 => Ok(Instruction::Lrem),
            114 => Ok(Instruction::Frem),
            115 => Ok(Instruction::Drem),
            116 => Ok(Instruction::Ineg),
            117 => Ok(Instruction::Lneg),
            118 => Ok(Instruction::Fneg),
            119 => Ok(Instruction::Dneg),
            120 => Ok(Instruction::Ishl),
            121 => Ok(Instruction::Lshl),
            122 => Ok(Instruction::Ishr),
            123 => Ok(Instruction::Lshr),
            124 => Ok(Instruction::Iushr),
            125 => Ok(Instruction::Lushr),
            126 => Ok(Instruction::Iand),
            127 => Ok(Instruction::Land),
            128 => Ok(Instruction::Ior),
            129 => Ok(Instruction::Lor),
            130 => Ok(Instruction::Ixor),
            131 => Ok(Instruction::Lxor),
            132 => Ok(Instruction::Iinc),
            133 => Ok(Instruction::I2l),
            134 => Ok(Instruction::I2f),
            135 => Ok(Instruction::I2d),
            136 => Ok(Instruction::L2i),
            137 => Ok(Instruction::L2f),
            138 => Ok(Instruction::L2d),
            139 => Ok(Instruction::F2i),
            140 => Ok(Instruction::F2l),
            141 => Ok(Instruction::F2d),
            142 => Ok(Instruction::D2i),
            143 => Ok(Instruction::D2l),
            144 => Ok(Instruction::D2f),
            145 => Ok(Instruction::I2b),
            146 => Ok(Instruction::I2c),
            147 => Ok(Instruction::I2s),
            148 => Ok(Instruction::Lcmp),
            149 => Ok(Instruction::Fcmpl),
            150 => Ok(Instruction::Fcmpg),
            151 => Ok(Instruction::Dcmpl),
            152 => Ok(Instruction::Dcmpg),
            153 => Ok(Instruction::Ifeq),
            154 => Ok(Instruction::Ifne),
            155 => Ok(Instruction::Iflt),
            156 => Ok(Instruction::Ifge),
            157 => Ok(Instruction::Ifgt),
            158 => Ok(Instruction::Ifle),
            159 => Ok(Instruction::If_icmpeq),
            160 => Ok(Instruction::If_icmpne),
            161 => Ok(Instruction::If_icmplt),
            162 => Ok(Instruction::If_icmpge),
            163 => Ok(Instruction::If_icmpgt),
            164 => Ok(Instruction::If_icmple),
            165 => Ok(Instruction::If_acmpeq),
            166 => Ok(Instruction::If_acmpne),
            167 => Ok(Instruction::Goto),
            168 => Ok(Instruction::Jsr),
            169 => Ok(Instruction::Ret),
            170 => Ok(Instruction::Tableswitch),
            171 => Ok(Instruction::Lookupswitch),
            172 => Ok(Instruction::Ireturn),
            173 => Ok(Instruction::Lreturn),
            174 => Ok(Instruction::Freturn),
            175 => Ok(Instruction::Dreturn),
            176 => Ok(Instruction::Areturn),
            177 => Ok(Instruction::Return),
            178 => Ok(Instruction::Getstatic),
            179 => Ok(Instruction::Putstatic),
            180 => Ok(Instruction::Getfield),
            181 => Ok(Instruction::Putfield),
            182 => Ok(Instruction::Invokevirtual),
            183 => Ok(Instruction::Invokespecial),
            184 => Ok(Instruction::Invokestatic),
            185 => Ok(Instruction::Invokeinterface),
            186 => Ok(Instruction::Invokedynamic),
            187 => Ok(Instruction::New),
            188 => Ok(Instruction::Newarray),
            190 => Ok(Instruction::Arraylength),
            191 => Ok(Instruction::Athrow),
            192 => Ok(Instruction::Checkcast),
            193 => Ok(Instruction::Instanceof),
            194 => Ok(Instruction::Monitorenter),
            195 => Ok(Instruction::Monitorexit),
            196 => Ok(Instruction::Wide),
            197 => Ok(Instruction::Multianewarray),
            198 => Ok(Instruction::Ifnull),
            199 => Ok(Instruction::Ifnonnull),
            200 => Ok(Instruction::Goto_w),
            201 => Ok(Instruction::Jsr_w),

            x => {
                return Err(CodeParseError::InvalidBytecode {
                    at: "here".to_string(),
                    what: format!("{}", x).to_string(),
                })
            }
        }
    }
}
