use crate::{io::BufferReadable, util::code_err::{CodeParseError, ClassParseError}};

#[repr(u8)]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Instruction {
    Nop,
    AconstNull,
    IconstM1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Lconst0,
    Lconst1,
    Fconst0,
    Fconst1,
    Fconst2,
    Dconst0,
    Dconst1,
    Bipush,
    Sipush,
    Ldc,
    LdcW,
    Ldc2W,
    Iload,
    Lload,
    Fload,
    Dload,
    Aload,
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Iaload,
    Laload,
    Faload,
    Daload,
    Aaload,
    Baload,
    Caload,
    Saload,
    Istore,
    Lstore,
    Fstore,
    Dstore,
    Astore,
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Iastore,
    Lastore,
    Fastore,
    Dastore,
    Aastore,
    Bastore,
    Castore,
    Sastore,
    Pop,
    Pop2,
    Dup,
    DupX1,
    DupX2,
    Dup2,
    Dup2X1,
    Dup2X2,
    Swap,
    Iadd,
    Ladd,
    Fadd,
    Dadd,
    Isub,
    Lsub,
    Fsub,
    Dsub,
    Imul,
    Lmul,
    Fmul,
    Dmul,
    Idiv,
    Ldiv,
    Fdiv,
    Ddiv,
    Irem,
    Lrem,
    Frem,
    Drem,
    Ineg,
    Lneg,
    Fneg,
    Dneg,
    Ishl,
    Lshl,
    Ishr,
    Lshr,
    Iushr,
    Lushr,
    Iand,
    Land,
    Ior,
    Lor,
    Ixor,
    Lxor,
    Iinc,
    I2l,
    I2f,
    I2d,
    L2i,
    L2f,
    L2d,
    F2i,
    F2l,
    F2d,
    D2i,
    D2l,
    D2f,
    I2b,
    I2c,
    I2s,
    Lcmp,
    Fcmpl,
    Fcmpg,
    Dcmpl,
    Dcmpg,
    Ifeq,
    Ifne,
    Iflt,
    Ifge,
    Ifgt,
    Ifle,
    IfIcmpeq,
    IfIcmpne,
    IfIcmplt,
    IfIcmpge,
    IfIcmpgt,
    IfIcmple,
    IfAcmpeq,
    IfAcmpne,
    Goto,
    Jsr,
    Ret,
    Tableswitch,
    Lookupswitch,
    Ireturn,
    Lreturn,
    Freturn,
    Dreturn,
    Areturn,
    Return,
    Getstatic,
    Putstatic,
    Getfield,
    Putfield,
    Invokevirtual,
    Invokespecial,
    Invokestatic,
    Invokeinterface,
    Invokedynamic,
    New,
    Newarray,
    Arraylength,
    Athrow,
    Checkcast,
    Instanceof,
    Monitorenter,
    Monitorexit,
    Wide,
    Multianewarray,
    Ifnull,
    Ifnonnull,
    GotoW,
    JsrW,
}

impl Instruction {
    pub fn load(reader: &mut Box<dyn BufferReadable>) -> Result<Instruction, ClassParseError> {
        match reader
            .read_byte()?
        {
            0 => Ok(Instruction::Nop),
            1 => Ok(Instruction::AconstNull),
            2 => Ok(Instruction::IconstM1),
            3 => Ok(Instruction::Iconst0),
            4 => Ok(Instruction::Iconst1),
            5 => Ok(Instruction::Iconst2),
            6 => Ok(Instruction::Iconst3),
            7 => Ok(Instruction::Iconst4),
            8 => Ok(Instruction::Iconst5),
            9 => Ok(Instruction::Lconst0),
            10 => Ok(Instruction::Lconst1),
            11 => Ok(Instruction::Fconst0),
            12 => Ok(Instruction::Fconst1),
            13 => Ok(Instruction::Fconst2),
            14 => Ok(Instruction::Dconst0),
            15 => Ok(Instruction::Dconst1),
            16 => Ok(Instruction::Bipush),
            17 => Ok(Instruction::Sipush),
            18 => Ok(Instruction::Ldc),
            19 => Ok(Instruction::LdcW),
            20 => Ok(Instruction::Ldc2W),
            21 => Ok(Instruction::Iload),
            22 => Ok(Instruction::Lload),
            23 => Ok(Instruction::Fload),
            24 => Ok(Instruction::Dload),
            25 => Ok(Instruction::Aload),
            26 => Ok(Instruction::Iload0),
            27 => Ok(Instruction::Iload1),
            28 => Ok(Instruction::Iload2),
            29 => Ok(Instruction::Iload3),
            30 => Ok(Instruction::Lload0),
            31 => Ok(Instruction::Lload1),
            32 => Ok(Instruction::Lload2),
            33 => Ok(Instruction::Lload3),
            34 => Ok(Instruction::Fload0),
            35 => Ok(Instruction::Fload1),
            36 => Ok(Instruction::Fload2),
            37 => Ok(Instruction::Fload3),
            38 => Ok(Instruction::Dload0),
            39 => Ok(Instruction::Dload1),
            40 => Ok(Instruction::Dload2),
            41 => Ok(Instruction::Dload3),
            42 => Ok(Instruction::Aload0),
            43 => Ok(Instruction::Aload1),
            44 => Ok(Instruction::Aload2),
            45 => Ok(Instruction::Aload3),
            46 => Ok(Instruction::Iaload),
            47 => Ok(Instruction::Laload),
            48 => Ok(Instruction::Faload),
            49 => Ok(Instruction::Daload),
            50 => Ok(Instruction::Aaload),
            51 => Ok(Instruction::Baload),
            52 => Ok(Instruction::Caload),
            53 => Ok(Instruction::Saload),
            54 => Ok(Instruction::Istore),
            55 => Ok(Instruction::Lstore),
            56 => Ok(Instruction::Fstore),
            57 => Ok(Instruction::Dstore),
            58 => Ok(Instruction::Astore),
            59 => Ok(Instruction::Istore0),
            60 => Ok(Instruction::Istore1),
            61 => Ok(Instruction::Istore2),
            62 => Ok(Instruction::Istore3),
            63 => Ok(Instruction::Lstore0),
            64 => Ok(Instruction::Lstore1),
            65 => Ok(Instruction::Lstore2),
            66 => Ok(Instruction::Lstore3),
            67 => Ok(Instruction::Fstore0),
            68 => Ok(Instruction::Fstore1),
            69 => Ok(Instruction::Fstore2),
            70 => Ok(Instruction::Fstore3),
            71 => Ok(Instruction::Dstore0),
            72 => Ok(Instruction::Dstore1),
            73 => Ok(Instruction::Dstore2),
            74 => Ok(Instruction::Dstore3),
            75 => Ok(Instruction::Astore0),
            76 => Ok(Instruction::Astore1),
            77 => Ok(Instruction::Astore2),
            78 => Ok(Instruction::Astore3),
            79 => Ok(Instruction::Iastore),
            80 => Ok(Instruction::Lastore),
            81 => Ok(Instruction::Fastore),
            82 => Ok(Instruction::Dastore),
            83 => Ok(Instruction::Aastore),
            84 => Ok(Instruction::Bastore),
            85 => Ok(Instruction::Castore),
            86 => Ok(Instruction::Sastore),
            87 => Ok(Instruction::Pop),
            88 => Ok(Instruction::Pop2),
            89 => Ok(Instruction::Dup),
            90 => Ok(Instruction::DupX1),
            91 => Ok(Instruction::DupX2),
            92 => Ok(Instruction::Dup2),
            93 => Ok(Instruction::Dup2X1),
            94 => Ok(Instruction::Dup2X2),
            95 => Ok(Instruction::Swap),
            96 => Ok(Instruction::Iadd),
            97 => Ok(Instruction::Ladd),
            98 => Ok(Instruction::Fadd),
            99 => Ok(Instruction::Dadd),
            100 => Ok(Instruction::Isub),
            101 => Ok(Instruction::Lsub),
            102 => Ok(Instruction::Fsub),
            103 => Ok(Instruction::Dsub),
            104 => Ok(Instruction::Imul),
            105 => Ok(Instruction::Lmul),
            106 => Ok(Instruction::Fmul),
            107 => Ok(Instruction::Dmul),
            108 => Ok(Instruction::Idiv),
            109 => Ok(Instruction::Ldiv),
            110 => Ok(Instruction::Fdiv),
            111 => Ok(Instruction::Ddiv),
            112 => Ok(Instruction::Irem),
            113 => Ok(Instruction::Lrem),
            114 => Ok(Instruction::Frem),
            115 => Ok(Instruction::Drem),
            116 => Ok(Instruction::Ineg),
            117 => Ok(Instruction::Lneg),
            118 => Ok(Instruction::Fneg),
            119 => Ok(Instruction::Dneg),
            120 => Ok(Instruction::Ishl),
            121 => Ok(Instruction::Lshl),
            122 => Ok(Instruction::Ishr),
            123 => Ok(Instruction::Lshr),
            124 => Ok(Instruction::Iushr),
            125 => Ok(Instruction::Lushr),
            126 => Ok(Instruction::Iand),
            127 => Ok(Instruction::Land),
            128 => Ok(Instruction::Ior),
            129 => Ok(Instruction::Lor),
            130 => Ok(Instruction::Ixor),
            131 => Ok(Instruction::Lxor),
            132 => Ok(Instruction::Iinc),
            133 => Ok(Instruction::I2l),
            134 => Ok(Instruction::I2f),
            135 => Ok(Instruction::I2d),
            136 => Ok(Instruction::L2i),
            137 => Ok(Instruction::L2f),
            138 => Ok(Instruction::L2d),
            139 => Ok(Instruction::F2i),
            140 => Ok(Instruction::F2l),
            141 => Ok(Instruction::F2d),
            142 => Ok(Instruction::D2i),
            143 => Ok(Instruction::D2l),
            144 => Ok(Instruction::D2f),
            145 => Ok(Instruction::I2b),
            146 => Ok(Instruction::I2c),
            147 => Ok(Instruction::I2s),
            148 => Ok(Instruction::Lcmp),
            149 => Ok(Instruction::Fcmpl),
            150 => Ok(Instruction::Fcmpg),
            151 => Ok(Instruction::Dcmpl),
            152 => Ok(Instruction::Dcmpg),
            153 => Ok(Instruction::Ifeq),
            154 => Ok(Instruction::Ifne),
            155 => Ok(Instruction::Iflt),
            156 => Ok(Instruction::Ifge),
            157 => Ok(Instruction::Ifgt),
            158 => Ok(Instruction::Ifle),
            159 => Ok(Instruction::IfIcmpeq),
            160 => Ok(Instruction::IfIcmpne),
            161 => Ok(Instruction::IfIcmplt),
            162 => Ok(Instruction::IfIcmpge),
            163 => Ok(Instruction::IfIcmpgt),
            164 => Ok(Instruction::IfIcmple),
            165 => Ok(Instruction::IfAcmpeq),
            166 => Ok(Instruction::IfAcmpne),
            167 => Ok(Instruction::Goto),
            168 => Ok(Instruction::Jsr),
            169 => Ok(Instruction::Ret),
            170 => Ok(Instruction::Tableswitch),
            171 => Ok(Instruction::Lookupswitch),
            172 => Ok(Instruction::Ireturn),
            173 => Ok(Instruction::Lreturn),
            174 => Ok(Instruction::Freturn),
            175 => Ok(Instruction::Dreturn),
            176 => Ok(Instruction::Areturn),
            177 => Ok(Instruction::Return),
            178 => Ok(Instruction::Getstatic),
            179 => Ok(Instruction::Putstatic),
            180 => Ok(Instruction::Getfield),
            181 => Ok(Instruction::Putfield),
            182 => Ok(Instruction::Invokevirtual),
            183 => Ok(Instruction::Invokespecial),
            184 => Ok(Instruction::Invokestatic),
            185 => Ok(Instruction::Invokeinterface),
            186 => Ok(Instruction::Invokedynamic),
            187 => Ok(Instruction::New),
            188 => Ok(Instruction::Newarray),
            190 => Ok(Instruction::Arraylength),
            191 => Ok(Instruction::Athrow),
            192 => Ok(Instruction::Checkcast),
            193 => Ok(Instruction::Instanceof),
            194 => Ok(Instruction::Monitorenter),
            195 => Ok(Instruction::Monitorexit),
            196 => Ok(Instruction::Wide),
            197 => Ok(Instruction::Multianewarray),
            198 => Ok(Instruction::Ifnull),
            199 => Ok(Instruction::Ifnonnull),
            200 => Ok(Instruction::GotoW),
            201 => Ok(Instruction::JsrW),

            x => {
                return Err(ClassParseError::CodeParseError { internal: CodeParseError::InvalidBytecode {
                    at: "here".to_string(),
                    what: format!("{}", x).to_string(),
                }, classpath: None, signature: None})
            }
        }
    }
}
